<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container84WjedP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container84WjedP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container84WjedP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container84WjedP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container84WjedP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '84WjedP',
    'container.build_id' => '82b4b608',
    'container.build_time' => 1584482654,
], __DIR__.\DIRECTORY_SEPARATOR.'Container84WjedP');
