<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJEJIT3I\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJEJIT3I/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJEJIT3I.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJEJIT3I\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJEJIT3I\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JEJIT3I',
    'container.build_id' => 'cc2fe634',
    'container.build_time' => 1584483692,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJEJIT3I');
